import type { ScenarioKey } from "./types";

export interface StepGuide {
  step: number;
  name: string;
  group: string;
  agent: string;
  information: string;
  execution: string;
  result: string;
}

const guides: Record<ScenarioKey, StepGuide[]> = {
  scenario1: [
    { step: 1, name: "Inventory existing NGSS alignment", group: "Standards Crosswalk", agent: "NGSS Alignment Inventory Agent", information: "Identify the NGSS standards and three-dimensional learning evidence already present in the product content.", execution: "Reads the uploaded product content, extracts standards citations, and structures the existing alignment inventory. Source files are analyzed; no source files are changed.", result: "A normalized inventory of implemented NGSS alignments, practices, core ideas, and crosscutting concepts." },
    { step: 2, name: "Crosswalk NGSS to South Carolina standards", group: "Standards Crosswalk", agent: "Standards Crosswalk Agent", information: "Compare the existing NGSS alignment with the supplied South Carolina standards reference.", execution: "Maps related NGSS expectations to South Carolina codes and records the relationship and supporting notes.", result: "A standards crosswalk showing matching, partial, and unmatched requirements." },
    { step: 3, name: "Identify South Carolina standards deltas", group: "Standards Crosswalk", agent: "Standards Delta Agent", information: "Determine what the state standards require beyond the existing NGSS-aligned content.", execution: "Compares the crosswalk against the state reference and isolates missing, changed, or additional expectations.", result: "A structured list of standards deltas requiring attention." },
    { step: 4, name: "Map performance targets", group: "Performance Target Mapping & Validation", agent: "Performance Target Agent", information: "Connect South Carolina performance targets to the content and standards identified so far.", execution: "Maps performance targets to lessons, evidence, and alignment records using the uploaded and configured reference documents.", result: "A performance-target map with traceable content relationships." },
    { step: 5, name: "Validate grade-level depth", group: "Performance Target Mapping & Validation", agent: "Grade-Level Depth Agent", information: "Check whether alignment is appropriate for the intended grade level and learning depth.", execution: "Reviews SEP, DCI, and CCC dimensions and compares their depth with grade-level expectations. This is a human review checkpoint.", result: "A validated grade-level depth assessment with findings requiring approval or adjustment." },
    { step: 6, name: "Define alignment criteria", group: "Content Alignment Review", agent: "Evidence Criteria Agent", information: "Establish consistent evidence rules for strong, partial, and gap classifications.", execution: "Creates explicit criteria that will be applied consistently to each state standard and its supporting evidence.", result: "A reusable alignment and evidence rubric." },
    { step: 7, name: "Review content evidence", group: "Content Alignment Review", agent: "Evidence Review Agent", information: "Inspect the actual product content for evidence supporting each claimed alignment.", execution: "Evaluates citations, activities, assessments, and instructional evidence against the defined criteria.", result: "An evidence review with traceable notes for each standard." },
    { step: 8, name: "Classify alignment coverage", group: "Content Alignment Review", agent: "Alignment Classification Agent", information: "Classify each requirement according to the evidence found.", execution: "Assigns Strong, Partial, or Gap classifications and records the rationale for every state requirement.", result: "A complete classification matrix with counts and explanations." },
    { step: 9, name: "Identify specific gaps", group: "Gap Analysis & Remediation", agent: "Gap Analysis Agent", information: "Turn classification gaps into concrete content and coverage problems.", execution: "Consolidates gap evidence, identifies affected standards, and describes what is missing or insufficient.", result: "A prioritized gap analysis tied back to standards and evidence." },
    { step: 10, name: "Recommend remediation", group: "Gap Analysis & Remediation", agent: "Remediation Agent", information: "Recommend practical changes that address each identified gap.", execution: "Generates targeted remediation recommendations while preserving traceability to the gap and standard.", result: "Actionable remediation recommendations for content owners." },
    { step: 11, name: "QA and finalize", group: "QA & Finalization", agent: "QA and Finalization Agent", information: "Check the complete crosswalk package for accuracy, consistency, completeness, and traceability.", execution: "Runs final quality checks and assembles the report, tables, recommendations, and exportable deliverables.", result: "The completed Scenario 1 standards crosswalk package." },
  ],
  scenario2: [
    { step: 1, name: "Collect and organize materials", group: "Gather & Organize", agent: "Intake Agent", information: "Prepare the candidate lessons and literacy strategy resource for analysis.", execution: "Registers uploaded files and organizes their extracted text for downstream agents. Inputs are read, not modified.", result: "A complete, traceable input set for the workflow." },
    { step: 2, name: "Identify lesson metadata", group: "Gather & Organize", agent: "Lesson Metadata Agent", information: "Extract the key metadata needed to compare candidate lessons.", execution: "Identifies grade, topic, objectives, duration, materials, and instructional structure from each lesson.", result: "Comparable metadata records for all candidate lessons." },
    { step: 3, name: "Extract literacy strategies", group: "Gather & Organize", agent: "Literacy Strategy Agent", information: "Understand the strategies available in the supplied literacy resource.", execution: "Parses the literacy reference and structures strategy names, demands, benefits, and implementation characteristics.", result: "A normalized literacy strategy catalog." },
    { step: 4, name: "Summarize candidate lessons", group: "Understand & Screen", agent: "Lesson Summary Agent", information: "Create concise summaries of each candidate lesson and its learning goals.", execution: "Condenses lesson content, objectives, activities, and assessment signals into comparable summaries.", result: "Structured lesson summaries for screening." },
    { step: 5, name: "Analyze literacy strategies", group: "Understand & Screen", agent: "Strategy Analysis Agent", information: "Evaluate the instructional demands and value of each literacy strategy.", execution: "Analyzes authentic literacy demand, science fit, communication benefit, risks, and implementation constraints.", result: "Strategy analysis records used in combination screening." },
    { step: 6, name: "Screen lesson-strategy combinations", group: "Understand & Screen", agent: "Combination Screening Agent", information: "Compare every candidate lesson with the available literacy strategy.", execution: "Scores combinations for instructional fit, science-learning depth, timing, duplication, and interference risk.", result: "A fit matrix and a recommended combination." },
    { step: 7, name: "Select the strongest combination", group: "Understand & Screen", agent: "Combination Review Agent", information: "Review the screening recommendation and choose the combination to develop.", execution: "Presents the fit matrix for human selection. No revision is applied until a reviewer submits a decision.", result: "The selected lesson-strategy combination." },
    { step: 8, name: "Conduct detailed lesson review", group: "Deep Instructional Analysis", agent: "Deep Review Agent", information: "Build a complete instructional picture of the selected lesson.", execution: "Reviews sequence, learning demands, student work, teacher actions, assessments, and constraints in the selected lesson.", result: "A deep instructional analysis for revision planning." },
    { step: 9, name: "Map literacy demands and supports", group: "Deep Instructional Analysis", agent: "Literacy Demand Agent", information: "Locate literacy demands and opportunities for strategic support.", execution: "Maps reading, writing, speaking, listening, and vocabulary demands to lesson activities and supports.", result: "A literacy-demand map with candidate support locations." },
    { step: 10, name: "Identify integration points", group: "Deep Instructional Analysis", agent: "Integration Point Agent", information: "Find moments where literacy integration can improve learning naturally.", execution: "Generates and scores candidate integration points, including activity impact, risks, and timing.", result: "A ranked set of integration candidates." },
    { step: 11, name: "Select the integration point", group: "Deep Instructional Analysis", agent: "Integration Review Agent", information: "Choose the integration point that best supports the lesson without disrupting science learning.", execution: "Presents candidates for human selection. The workflow waits for a reviewer decision.", result: "The approved integration point for revision." },
    { step: 12, name: "Define instructional purpose", group: "Revision Planning", agent: "Revision Planning Agent", information: "Define what the literacy integration is intended to accomplish.", execution: "Specifies the instructional purpose, learner benefit, success conditions, and affected lesson elements.", result: "A clear instructional purpose for the revision." },
    { step: 13, name: "Identify affected components", group: "Revision Planning", agent: "Revision Planning Agent", information: "Determine which connected lesson materials must change together.", execution: "Traces dependencies across student content, teacher guidance, assessments, timing, and supporting components.", result: "A connected-component impact map." },
    { step: 14, name: "Assess timing and lesson flow", group: "Revision Planning", agent: "Revision Planning Agent", information: "Confirm the planned integration fits the lesson flow and available time.", execution: "Assesses duration, transitions, pacing, and instructional integrity before drafting begins.", result: "A timing-aware revision plan." },
    { step: 15, name: "Draft student-facing content", group: "Content Development", agent: "Student Content Agent", information: "Write the revised student-facing lesson content.", execution: "Drafts activities, prompts, directions, and student supports using the approved integration plan.", result: "Updated student-facing content." },
    { step: 16, name: "Draft teacher guidance", group: "Content Development", agent: "Teacher Content Agent", information: "Provide teachers with guidance to implement the integrated strategy.", execution: "Creates teacher directions, facilitation notes, scaffolds, and look-fors aligned to the student experience.", result: "Updated teacher-facing guidance." },
    { step: 17, name: "Update connected components", group: "Content Development", agent: "Connected Components Agent", information: "Synchronize related lesson components with the revision.", execution: "Updates assessments, materials, timing, references, and other connected elements to remove contradictions.", result: "A coherent set of connected lesson updates." },
    { step: 18, name: "Write revision rationale", group: "Content Development", agent: "Rationale Agent", information: "Document why the changes were made and what they improve.", execution: "Records evidence, design reasoning, literacy benefit, science benefit, and instructional impact.", result: "A traceable revision rationale." },
    { step: 19, name: "Validate literacy fidelity", group: "Quality Assurance", agent: "Literacy QA Agent", information: "Check that the selected literacy strategy is implemented faithfully.", execution: "Tests the draft against strategy characteristics, literacy demands, supports, and intended use.", result: "Literacy fidelity findings." },
    { step: 20, name: "Validate science accuracy", group: "Quality Assurance", agent: "Science QA Agent", information: "Protect the accuracy and rigor of the science learning.", execution: "Reviews science claims, objectives, content, standards, and assessments for accuracy and alignment.", result: "Science accuracy findings." },
    { step: 21, name: "Validate instructional integrity", group: "Quality Assurance", agent: "Instructional QA Agent", information: "Ensure the revision preserves sound instructional design.", execution: "Checks learning outcomes, scaffolding, usability, cognitive demand, and instructional coherence.", result: "Instructional integrity findings." },
    { step: 22, name: "Review coherence and pacing", group: "Quality Assurance", agent: "Coherence QA Agent", information: "Check that the revised lesson reads and flows as one experience.", execution: "Reviews transitions, pacing, sequence, and the relationship between teacher and student materials.", result: "Coherence and pacing findings." },
    { step: 23, name: "Check cross-component consistency", group: "Quality Assurance", agent: "Consistency QA Agent", information: "Find contradictions or mismatches across all revised components.", execution: "Compares terminology, directions, timing, assessments, and references across the package.", result: "A consolidated consistency review." },
    { step: 24, name: "Review QA feedback", group: "Quality Assurance", agent: "QA Review Agent", information: "Review the five QA passes and decide what feedback to accept.", execution: "Presents findings and issues for human review. No automatic content change occurs at this screen.", result: "Approved QA decisions for incorporation." },
    { step: 25, name: "Incorporate feedback", group: "Finalization", agent: "Revision Agent", information: "Apply the approved QA decisions to the revised content.", execution: "Updates affected content and connected components based on the review decisions.", result: "A corrected revision package." },
    { step: 26, name: "Re-review modified content", group: "Finalization", agent: "Re-review Agent", information: "Confirm that changes resolved the accepted QA issues.", execution: "Rechecks modified areas and verifies that fixes did not introduce new inconsistencies.", result: "A final validation of the corrected content." },
    { step: 27, name: "Finalize revision package", group: "Finalization", agent: "Finalization Agent", information: "Assemble the complete final literacy integration package.", execution: "Combines student content, teacher guidance, rationale, connected updates, QA outcomes, and export data.", result: "The completed Scenario 2 final revision package." },
  ],
  scenario3: [
    { step: 1, name: "Identify grade level", group: "Gather & Organize", agent: "Grade Identification Agent", information: "Confirm the grade level represented by the uploaded unit materials.", execution: "Extracts and validates grade-level signals from the scope and sequence and lesson documents.", result: "A confirmed grade level for standards analysis." },
    { step: 2, name: "Acquire state standards", group: "Gather & Organize", agent: "Standards Acquisition Agent", information: "Parse the authoritative state standards supplied for the unit.", execution: "Structures standards identifiers, descriptions, and expectations from the uploaded reference document.", result: "A normalized state standards reference." },
    { step: 3, name: "Extract C3 alignment", group: "Gather & Organize", agent: "C3 Alignment Agent", information: "Identify the unit's existing C3 Framework alignment.", execution: "Extracts current standards, codes, and alignment evidence from the scope-and-sequence.", result: "An inventory of existing unit alignment." },
    { step: 4, name: "Build standards crosswalk", group: "Gather & Organize", agent: "Crosswalk Agent", information: "Map existing C3 alignment to the target state standards.", execution: "Creates relationships between existing codes and state standards and records unmatched requirements.", result: "A complete preliminary crosswalk." },
    { step: 5, name: "Review crosswalk", group: "Gather & Organize", agent: "Crosswalk Review Agent", information: "Validate the proposed standards crosswalk before mapping lesson coverage.", execution: "Presents the crosswalk for human review and captures corrections or approval.", result: "An approved standards crosswalk." },
    { step: 6, name: "Summarize lesson content", group: "Read & Map", agent: "Lesson Summary Agent", information: "Create structured summaries of the unit's lesson and support files.", execution: "Extracts objectives, activities, evidence, and instructional sequence from each lesson.", result: "Comparable lesson summaries." },
    { step: 7, name: "Map lessons to state standards", group: "Read & Map", agent: "Standards Mapping Agent", information: "Determine how each lesson contributes to state standards coverage.", execution: "Maps lesson evidence to state standards and records coverage status and supporting detail.", result: "A lesson-to-standard alignment map." },
    { step: 8, name: "Review alignment map", group: "Read & Map", agent: "Alignment Review Agent", information: "Validate the lesson coverage classifications and evidence.", execution: "Presents the alignment map for human review and records adjustments or approval.", result: "An approved alignment map." },
    { step: 9, name: "Compile gap list", group: "Gap Analysis", agent: "Gap Analysis Agent", information: "Identify state standards not adequately covered by the unit.", execution: "Consolidates uncovered and under-covered standards with evidence and impact details.", result: "A structured list of alignment gaps." },
    { step: 10, name: "Identify surplus content", group: "Gap Analysis", agent: "Surplus Content Agent", information: "Find lesson content that exceeds or sits outside the target standards.", execution: "Compares lesson content with the standards reference and records surplus or reassignment candidates.", result: "A surplus-content inventory." },
    { step: 11, name: "Plan and place revisions", group: "Revision Planning", agent: "Revision Planning Agent", information: "Plan where and how revisions will address gaps and surplus content.", execution: "Creates revision interventions, target lessons, placement locations, timing, and rationale.", result: "A detailed revision plan." },
    { step: 12, name: "Review revision plan", group: "Revision Planning", agent: "Revision Review Agent", information: "Validate that the proposed revisions are practical and complete.", execution: "Presents the plan for human review and captures approval or changes.", result: "An approved revision plan." },
    { step: 13, name: "Draft revised content", group: "Content Drafting", agent: "Content Drafting Agent", information: "Draft lesson content that addresses the approved revision plan.", execution: "Writes revised activities, supports, and learning evidence for the targeted lessons.", result: "Draft revised lesson content." },
    { step: 14, name: "Write revision rationale", group: "Content Drafting", agent: "Rationale Agent", information: "Explain the alignment reason and expected benefit for every revision.", execution: "Links each change to a gap, standard, lesson location, and instructional rationale.", result: "Traceable rationale entries." },
    { step: 15, name: "Update scope and sequence", group: "Content Drafting", agent: "Scope and Sequence Agent", information: "Reflect the revisions in the unit-level scope and sequence.", execution: "Updates sequence, standards references, lesson placement, and coverage notes to match revised content.", result: "An updated scope-and-sequence document." },
    { step: 16, name: "Complete quality assurance", group: "Quality Assurance", agent: "Quality Assurance Agent", information: "Verify that the final alignment package is accurate, coherent, and editorially ready.", execution: "Runs coherence, coverage, and editorial checks and assembles the final package and export data.", result: "The completed Scenario 3 standards alignment package." },
  ],
};

export function getStepGuide(scenario: ScenarioKey, step: number): StepGuide | null {
  return guides[scenario]?.find((guide) => guide.step === step) ?? null;
}

export function getStepGuides(scenario: ScenarioKey): StepGuide[] {
  return guides[scenario] ?? [];
}
