"""Background execution of graph runs + an in-memory registry for state the checkpointer can't
tell us on its own (mainly: did the last background invocation crash, and why).

Generic across scenarios: every function takes the compiled graph to operate on as its first
argument, so the same executor/error-registry machinery serves Scenario 2, Scenario 3, and any
future scenario without duplication. Run ids are UUIDs generated by the API layer and are unique
across scenarios, so the single shared error registry (keyed by run_id) is safe to share too.
"""

from __future__ import annotations

import threading
import traceback
from concurrent.futures import ThreadPoolExecutor
from typing import Any

from langgraph.types import Command

_executor = ThreadPoolExecutor(max_workers=4)
_lock = threading.Lock()
_run_errors: dict[str, str] = {}

# LangGraph's own ``Command(resume=...)`` treats a literal ``None`` as "there is no resume value
# at all" (see pregel/_loop.py's ``_first``) -- passing None there hits an unrelated internal
# UnboundLocalError instead of resuming. Our checkpoint nodes want "the human passed no override,
# use the AI's recommendation" to be expressible too, so every caller that means that must send
# this sentinel instead of None/null. Every checkpoint node checks for it explicitly rather than
# doing a truthiness check, so a real override that happens to be falsy (an empty list of edits,
# say) is never mistaken for "no override".
NO_OVERRIDE = "__accept_ai_recommendation__"


def _config(run_id: str) -> dict:
    return {"configurable": {"thread_id": run_id}}


def _invoke(graph: Any, run_id: str, payload: Any) -> None:
    try:
        graph.invoke(payload, config=_config(run_id))
        with _lock:
            _run_errors.pop(run_id, None)
    except Exception:  # noqa: BLE001 - surfaced to the API layer, not swallowed
        with _lock:
            _run_errors[run_id] = traceback.format_exc()


def start_run(graph: Any, run_id: str, initial_state: dict) -> None:
    _executor.submit(_invoke, graph, run_id, initial_state)


def resume_run(graph: Any, run_id: str, resume_value: Any) -> None:
    _executor.submit(_invoke, graph, run_id, Command(resume=resume_value))


def get_last_error(run_id: str) -> str | None:
    with _lock:
        return _run_errors.get(run_id)


def get_state(graph: Any, run_id: str):
    return graph.get_state(_config(run_id))
